language: node_js
node_js:
- stable
install:
- npm install
script:
- npm run cover
- npm run report
- npm run document
after_script: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
after_success:
- ".travis/push.sh"
env:
  global:
    secure: jc/c+GjIjjAeJ0lZKEOaSYHTsBDOLsO5+mXWCbhu1Y7cFOw7DwofcUF4kfxt80KKVRplOCHm9Dz8KWNAlgrTTfwdIWJCXx0lHHGaFR6Wk9ptEIAj5ugV9vnzik9bFzufiW9CtzNsyjW040SPL9+VTWuLCyR4w7Smk7TSOKPaAy7DzZdRGHn4GebkpZorVcYqMPWSDhKV5Pj2qz2DapCtOG1KSGBpLGgAZ+DtX3V9xV9IJ901VabajGbXx5jt0lJP/0ThHpxo8xK4OiqVpDlllT7ujtaF1RqcZ1Ws11D5bm12rYm6dS/u5mtvukWTcta94mNd0jxu/r0qyWXuP76XRDYS4FBVZkLRfPJjOYJuPLWX0qqCzmArsEaEL3QvxIQLILkmscJ/Let58k5TVSCU9DppfdJQ/bycH25g3o8TymxcHGa66rdeEIbrgrsXpy+mAxLA+fLoYunW6AiACOFPKKGrCbLAeTV7BdGD+N71tr2fls7w1DUZONB4j/5za2YtaHccNtJeT2rj0azUDhzvQQ5kvoVfcjldpD1CbruQhZp/k+C9xnbZHS0xNofpXc/GEfxYNFr2FX60B8sEtQmLDCJJHVBle1Owtwy4tX0I5yBTPjky9q4K15nvQBH9nYfQ0khiqMEH85KQaj6/7sIBBLsnGeXvIki9MZNM5IuMe1E=
